### ISSUE TITLE
评论功能可以加一个giscus的driver吗？

### ISSUE THREAD

**Issue by hxhac** [cirry/astro-yi#13]
Waline需要部署，对于blog来说，还是稍微重了点

博客非常棒，非常漂亮，感谢你的分享

**Comment by cirry** [comment]
好建议，已经添加了。[00c4510](https://github.com/cirry/astro-yi/commit/00c4510b354fbff5f75e37c1bcbc31df349c5ac4)

**Comment by hxhac** [comment]
太感谢了 @cirry
