### ISSUE TITLE
怎么开启对astro内置Admonitions的支持呢？

### ISSUE THREAD

**Issue by hxhac** [cirry/astro-yi#16]
比如 [docs/src/content/docs/zh-cn/basics/astro-components.mdx at main · withastro/docs](https://github.com/withastro/docs/blob/main/src/content/docs/zh-cn/basics/astro-components.mdx?plain=1#L55) 中的

```markdown
:::tip

:::

```

这种语法

---

另外，还有个小建议哈，能否把该theme做成类似 [withastro/starlight: 🌟 Build beautiful, accessible, high-performance documentation websites with Astro](https://github.com/withastro/starlight) 的template，否则很难追踪到您后续添加的feats，感谢

**Comment by cirry** [comment]
后面我加一下这功能

**Comment by hxhac** [comment]
okk

**Comment by cirry** [comment]
已经添加了，效果在这[astro-yi new-features](https://astro-yi-nu.vercel.app/blog/new-features)
